### ISSUE TITLE
Error in creating URI

### ISSUE THREAD

**Issue by matteoLorenzini** [gtadigital/Xml_RDF_mapping#23]
**Describe the bug**
Some URIs are not created according to the policy file

**To Reproduce**

```

<crm:E55_Type rdf:about="144521-E55_Type">

```

**Expected behavior**

```
<crm:E55_Type rdf:about="urn:uuid:cd2986c3-3195-4f75-a65b-437e6c2e556a"/>
```
If multiple UUIDs are used, they must be different between each others

**Comment by ZCRNK** [comment]
In the test I ran with the updated version of xml_to_rdf_mapper.py all uuids are unique now
